name: Run Cypress Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  gothru-dashboard-cypress-tests:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Cache Cypress binary
        uses: actions/cache@v4
        with:
          path: C:\Users\runneradmin\AppData\Local\Cypress\Cache
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-cypress-

      # ✅ Tambahkan install Cypress untuk memastikan binary ada
      - name: Install Cypress
        run: npx cypress install

      - name: Run Cypress tests
        run: npx cypress run --browser chrome --headless

      - name: Upload Cypress test results (HTML)
        uses: actions/upload-artifact@v4
        with:
          name: cypress-html-report
          path: cypress/results/*.html

      - name: Upload Cypress test results (JSON)
        uses: actions/upload-artifact@v4
        with:
          name: cypress-json-report
          path: cypress/results/*.json